# Generated by Django 3.1.3 on 2020-11-02 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_orientation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_role',
            field=models.CharField(choices=[('EMPLOYEE', 'EMPLOYEE'), ('MENTOR', 'MENTOR')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='training_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_orientation.training'),
        ),
    ]
