# Generated by Django 3.1.3 on 2020-11-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_orientation', '0002_auto_20201102_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='assigned_project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_orientation.project'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_role',
            field=models.CharField(choices=[('TRAINEE', 'TRAINEE'), ('MENTOR', 'MENTOR')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='training_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_orientation.training'),
        ),
    ]
