# Generated by Django 3.1.3 on 2020-11-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_orientation', '0006_auto_20201105_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_role',
            field=models.CharField(blank='', choices=[('TRAINEE', 'TRAINEE'), ('MENTOR', 'MENTOR')], max_length=10, null=True),
        ),
    ]
