# Generated by Django 3.1.3 on 2020-11-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_orientation', '0007_auto_20201105_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_role',
            field=models.CharField(choices=[('TRAINEE', 'TRAINEE'), ('MENTOR', 'MENTOR')], max_length=10, null=True),
        ),
    ]
