# Generated by Django 3.1.3 on 2020-11-12 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_orientation', '0009_auto_20201107_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
